# Generated by Django 4.1.4 on 2022-12-09 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("things", "0002_remove_thing_username")]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        )
    ]
