# Generated by Django 4.1.4 on 2022-12-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("things", "0003_alter_thing_quantity")]

    operations = [
        migrations.RenameField(
            model_name="thing", old_name="desc", new_name="description"
        )
    ]
